apiVersion: v1
kind: Template
metadata:
  name: wildfly-mongo
message: You can connect to the database using MongoDB connection URL mongodb://${DB_USERNAME}:${DB_PASSWORD}@${APPLICATION_NAME}-data:27017/${DB_DATABASE}
objects:
### Application Layer: WildFly
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name":"${APPLICATION_NAME}-data","namespace":"","kind":"Service"}]'
      description: The web server's http port.
    labels:
      component: application-server
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-app
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      component: application-server
      application: ${APPLICATION_NAME}
      deploymentConfig: ${APPLICATION_NAME}-app
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      component: application-server
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-app
  spec:
    replicas: 1
    selector:
      component: application-server
      application: ${APPLICATION_NAME}
      deploymentConfig: ${APPLICATION_NAME}-app
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          component: application-server
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}-app
        name: ${APPLICATION_NAME}-app
      spec:
        containers:
        - env:
          - name: DB_SERVICE
            value: ${APPLICATION_NAME}-data
          - name: DB_USERNAME
            value: ${DB_USERNAME}
          - name: DB_PASSWORD
            value: ${DB_PASSWORD}
          - name: DB_DATABASE
            value: ${DB_DATABASE}
          image: ' '
          imagePullPolicy: IfNotPresent
          name: wildfly-mongo-alpine
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - wildfly-mongo-alpine
        from:
          kind: ImageStreamTag
          name: wildfly-alpine:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  id: ${APPLICATION_NAME}-app
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      component: application-server
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-app
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}-app
### Persistent Layer: MongoDB
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      component: database
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-data
  spec:
    replicas: 1
    selector:
      component: database
      application: ${APPLICATION_NAME}
      deploymentConfig: ${APPLICATION_NAME}-data
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          component: database
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}-data
        name: ${APPLICATION_NAME}-data
      spec:
        containers:
        - env:
          - name: MONGODB_USER
            value: ${DB_USERNAME}
          - name: MONGODB_PASSWORD
            value: ${DB_PASSWORD}
          - name: MONGODB_DATABASE
            value: ${DB_DATABASE}
          - name: MONGODB_ADMIN_PASSWORD
            value: ${DB_ADMIN_PASSWORD}
          - name: MONGODB_NOPREALLOC
            value: ${MONGODB_NOPREALLOC}
          - name: MONGODB_SMALLFILES
            value: ${MONGODB_SMALLFILES}
          - name: MONGODB_QUIET
            value: ${MONGODB_QUIET}
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:latest
          namespace: openshift
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The database server's port.
    labels:
      component: database
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-data
  spec:
    ports:
    - port: 27017
      targetPort: 27017
    selector:
      component: database
      application: ${APPLICATION_NAME}
      deploymentConfig: ${APPLICATION_NAME}-data
parameters:
- description: Application's name
  name: APPLICATION_NAME
  required: true
  value: microservice
- description: Disable data file preallocation.
  name: MONGODB_NOPREALLOC
- description: Set MongoDB to use a smaller default data file size.
  name: MONGODB_SMALLFILES
- description: Runs MongoDB in a quiet mode that attempts to limit the amount of output.
  name: MONGODB_QUIET
- description: Database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: DB_USERNAME
  required: true
- description: Database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: DB_PASSWORD
  required: true
- description: Database admin password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: DB_ADMIN_PASSWORD
  required: true
- description: Database name
  name: DB_DATABASE
  required: true
  value: sampledb



